import React from 'react'
import Layout from "../components/Layout"
import LandingTextDisplay from '../components/LandingTextDisplay'
import LandingImageArea from '../components/LandingImageArea'
import aboutStyles from "../styles/pages/about.module.scss"
import ProgressBar from "../components/ProgressBar"

export default function About() {
    return (
        <Layout page="about" bgColor="inherit">
            <div className={aboutStyles.about__wrapper}>
            <div className={aboutStyles.maindiv}>
                <div className={aboutStyles.hero__display}>
                    <LandingTextDisplay style={aboutStyles.text__display__area}/>
                    <LandingImageArea style={aboutStyles.image__display__area}/>
                </div>
                <div className={aboutStyles.slider__display__area}>
                    <ProgressBar title='html' width='100'/>
                    <ProgressBar title='css' width='90'/>
                    <ProgressBar title='javascript' width='70'/>
                    <ProgressBar title='react' width='20'/>
                    <ProgressBar title='vue' width='80'/>
                    <ProgressBar title='jquery' width='50'/>
                </div>
            </div>
            <div className={aboutStyles.right__display}>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellat non excepturi asperiores voluptates maxime ad eveniet nesciunt culpa cupiditate. Omnis, vitae iure. Quas perferendis earum nesciunt at cumque ducimus eum est laudantium aut optio nam vel iure nostrum voluptas, obcaecati dolorum quo harum ipsam expedita, placeat repellat. Sit odit aliquam earum eveniet magni aut, quae nihil pariatur fugit, quas dolorem vero itaque atque magnam libero consequatur porro, expedita quod? Sunt veniam, quis recusandae eius repellendus pariatur voluptatibus corporis. Dicta iste magni natus. Hic a consectetur ducimus nam maxime quaerat, impedit reiciendis temporibus mollitia sunt harum odio sed? Velit rem alias quae porro excepturi. Ab temporibus fugit, excepturi dignissimos repellendus ducimus soluta quam in odio dolorum. Ipsam ducimus dolorum placeat nam doloremque corporis ad iste non odit facilis magni quia cupiditate, molestias saepe quos quas nobis, repellat omnis ipsum perspiciatis quasi atque excepturi. Officiis blanditiis cupiditate suscipit, cumque optio error libero, ipsum dolores modi odit esse architecto eligendi iste incidunt debitis laudantium commodi inventore nulla, autem eos. Odio, consectetur nulla. Consequatur cupiditate iusto non accusantium, maxime saepe in omnis laboriosam laudantium modi neque doloremque unde dolor, facere, consequuntur maiores. Accusantium aspernatur deleniti dolorem perferendis minima! Neque, cumque. Id doloremque earum inventore! 
            </div>
            </div>
        </Layout>
    )
}